[theme]
    dark     = 'catppuccin_macchiato'
    light    = 'catppuccin_latte'
    fallback = 'catppuccin_frappe'

[keys]
    [keys.normal]
        A-z = 'suspend'
        A-l = ':lsp-restart'
        A-k = [ 'extend_to_line_bounds', 'delete_selection', 'paste_after' ]
        A-i = [
            'extend_to_line_bounds',
            'delete_selection',
            'move_line_up',
            'paste_before'
        ]

        A-p = 'replace_selections_with_clipboard'
        A-y = [
            'extend_to_line_bounds',
            'yank_to_clipboard',
            'delete_selection_noyank'
        ]
        A-n = 'vsplit_new'
        A-r = [ ':reload' ]
        A-R = [ ':config-reload', ':redraw' ]

        C-x = ':write-buffer-close'
        C-X = ':write-quit'
        C-W = ':write-quit-all --no-format'
        C-n = 'hsplit_new'
        C-b = 'transpose_view'

        C-k   = [ 'move_line_down', 'goto_line_start', 'extend_to_line_end' ]
        C-i   = [ 'move_line_up', 'goto_line_start', 'extend_to_line_end' ]
        C-s   = [ ':format', ':write' ]
        C-S   = ':write! --no-format'
        C-r   = 'replace'
        C-o   = ':config-open'
        C-z   = 'undo'
        C-y   = 'redo'
        C-L   = ':open ~/.config/helix/languages.toml'
        C-f   = [ ':format' ]
        C-ret = [ 'open_below', 'normal_mode' ]
        C-q   = ':quit'

        ret      = 'insert_newline'
        up       = ':noop'
        down     = ':noop'
        left     = ':noop'
        right    = ':noop'
        home     = ':noop'
        end      = ':noop'
        pageup   = ':noop'
        pagedown = ':noop'
        ins      = 'insert_mode'

        q = ':noop'
        Q = ':quit!'
        a = 'code_action'
        n = 'insert_mode'
        N = 'append_mode'
        u = 'open_below'
        o = 'open_above'
        k = 'move_line_down'
        j = 'move_char_left'
        i = 'move_line_up'
        l = 'move_char_right'
        h = [ 'extend_to_line_bounds', 'hover', 'keep_primary_selection' ]
        H = [ 'extend_to_line_bounds', 'hover', 'keep_primary_selection' ]
        D = 'diagnostics_picker'
        r = 'select_regex'
        R = [
            'save_selection',
            'goto_file_start',
            'align_view_top',
            'select_all',
            'select_regex',
            'normal_mode'
        ]

        "="       = 'page_cursor_half_up'
        minus     = 'page_cursor_half_down'
        del       = [ 'extend_char_right', 'delete_selection_noyank' ]
        backspace = [ 'move_char_left', 'delete_selection_noyank' ]
        S-tab     = 'move_parent_node_start'
        tab       = 'move_parent_node_end'

        f.n = 'find_next_char'
        f.p = 'find_prev_char'
        f.t = 'find_till_char'

        M.r = 'record_macro'
        M.p = 'replay_macro'

        s.s = 'search'
        s.r = 'rsearch'
        s.g = 'global_search'

        p.f = 'file_picker_in_current_buffer_directory'
        p.F = 'file_picker'
        p.e = 'file_explorer'
        p.E = 'file_explorer_in_current_buffer_directory'
        p.s = 'lsp_or_syntax_symbol_picker'
        p.b = 'buffer_picker'
        p.l = 'last_picker'
        p.j = 'jumplist_picker'

        y.y = 'yank'
        y.j = 'yank_joined'
        y.r = 'replace_with_yanked'
        y.a = 'paste_after'
        y.b = 'paste_before'

        Y.y = ':primary-clipboard-yank'
        Y.j = ':primary-clipboard-yank-join'
        Y.r = ':primary-clipboard-paste-replace'
        Y.a = ':primary-clipboard-paste-after'
        Y.b = ':primary-clipboard-paste-before'

        "/" = 'command_mode'
        "?" = 'command_palette'

    [keys.insert]
        A-k = [ 'extend_to_line_bounds', 'delete_selection', 'paste_after' ]
        A-i = [
            'extend_to_line_bounds',
            'delete_selection',
            'move_line_up',
            'paste_before'
        ]
        A-p = 'replace_selections_with_clipboard'

        C-y = 'redo'
        C-z = 'undo'
        C-f = [ ':format', 'keep_primary_selection', 'normal_mode' ]
        C-n = 'normal_mode'
        C-p = [
            'extend_to_line_bounds',
            'yank_to_clipboard',
            'delete_selection_noyank'
        ]

        C-s   = [ 'normal_mode', ':format', ':write' ]
        S-tab = 'move_parent_node_start'

    [keys.select]
        S-tab = 'extend_parent_node_start'
        tab   = 'extend_parent_node_end'

        k = 'extend_line_down'
        j = 'extend_prev_char'
        i = 'extend_line_up'
        l = 'extend_next_char'
        V = 'keep_primary_selection'

[editor]
    auto-completion          = true
    bufferline               = 'multiple'
    cursorline               = true
    shell                    = [ '/usr/bin/nu', '--commands' ]
    rainbow-brackets         = true
    trim-final-newlines      = true
    trim-trailing-whitespace = true
    clipboard-provider       = 'termcode'
    kitty-keyboard-protocol  = 'enabled'

    [editor.cursor-shape]
        insert = 'bar'
        normal = 'underline'
        select = 'block'

    [editor.file-explorer]
        hidden     = false
        git-ignore = false
        git-global = true
        parents    = true

    [editor.lsp]
        auto-document-highlight   = true
        display-inlay-hints       = true
        display-progress-messages = true
        inlay-hints-length-limit  = 10

    [editor.auto-save]
        after-delay = { enable = false, timeout = 30000 }
        focus-lost  = true

    [editor.indent-guides]
        character = '▏'
        render    = true

    [editor.inline-diagnostics]
        cursor-line     = 'hint'
        other-lines     = 'disable'
        max-diagnostics = 1

    [editor.word-completion]
        trigger-length = 5
