explicit_optional_access   = false
max_pipeline_length        = 80
pipeline_placement         = "start"
sequential                 = false
skip_external_parse_errors = true

[groups]

[rules]
check_typed_flag_before_use = "off"
missing_in_type             = "off"
missing_out_type            = "off"
reflow_wide_lists           = "off"
