[language-server]
superhtml = { command = 'superhtml', args = ['lsp', '--syntax-only'] }

[[language]]
auto-format      = true
formatter        = { command = "nufmt", args = ["--stdin"] }
name             = "nu"

[[language]]
auto-format = true
language-servers = ["tombi"]
name = "toml"

[[language]]
indent = { tab-size = 4, unit = " "}
auto-format      = true
file-types       = ["json", "jsonl", "code-workspace"]
language-servers = ["vscode-json-language-server"]
name             = "json"


[[language]]
auto-format = true
name = 'html'
file-types = ['html', 'xml']
formatter = { command = "superhtml", args = ["fmt", "--stdin", "--syntax-only"]}
