[use-grammars]
only = [
    "awk",
    "bash",
    "bibtex",
    "c",
    "c-sharp",
    "cmake",
    "comment",
    "cpp",
    "css",
    "csv",
    "cython",
    "debian",
    "diff",
    "dockerfile",
    "fish",
    "git-config",
    "git-rebase",
    "graphql",
    "hosts",
    "html",
    "ini",
    "ink",
    "java",
    "javascript",
    "jq",
    "jsdoc",
    "json",
    "json5",
    "just",
    "kdl",
    "latex",
    "llvm",
    "log",
    "mail",
    "make",
    "markdown",
    "matlab",
    "mermaid",
    "nginx",
    "nu",
    "passwd",
    "pem",
    "php",
    "powershell",
    "properties",
    "python",
    "regex",
    "robot",
    "rshtml",
    "rust",
    "rust-format-args",
    "scss",
    "sql",
    "sshclientconfig",
    "svelte",
    "task",
    "todotxt",
    "toml",
    "tsx",
    "typescript",
    "xml",
    "yaml",
]

[language-server]
superhtml = { command = "superhtml", args = ["lsp", "--syntax-only"] }

[[language]]
auto-format = true
formatter   = { command = "nufmt", args = ["--stdin"] }
name        = "nu"

[[language]]
language-servers = ["tombi"]
name             = "toml"

[[language]]
comment-tokens = "//"
file-types     = ["json", "jsonc", "json5", "code-workspace"]
indent         = { tab-width = 4, unit = " " }
name           = "json"


[[language]]
auto-format = true
file-types = ["html", "xml"]
formatter = { command = "superhtml", args = [
    "fmt",
    "--stdin",
    "--syntax-only",
] }
language-servers = ["superhtml"]
name = "html"
soft-wrap = { enable = true }
