toml-version = 'v1.0.0'

[format]
    [format.rules]
        array-bracket-space-width         = 1
        array-comma-space-width           = 1
        date-time-delimiter               = 'space'
        indent-style                      = 'space'
        indent-sub-tables                 = true
        indent-table-key-value-pairs      = true
        indent-width                      = 4
        inline-table-brace-space-width    = 1
        inline-table-comma-space-width    = 1
        key-value-equals-sign-alignment   = true
        key-value-equals-sign-space-width = 1
        line-ending                       = 'lf'
        line-width                        = 80
        string-quote-style                = 'single'
        trailing-comment-alignment        = true
        trailing-comment-space-width      = 2

[lint]
    [lint.rules]
        dotted-keys-out-of-order = 'error'
        key-empty                = 'error'
        tables-out-of-order      = 'warn'

[lsp]
    code-action.enabled          = true
    completion.enabled           = true
    diagnostic.enabled           = true
    document-link.enabled        = true
    formatting.enabled           = true
    goto-declaration.enabled     = true
    goto-definition.enabled      = true
    goto-type-definition.enabled = true
    hover.enabled                = true
    workspace-diagnostic.enabled = true

[schema]
    enabled = true
    strict  = true
    catalog = {
        paths = [
            'tombi://www.schemastore.org/api/json/catalog.json',
            'https://www.schemastore.org/api/json/catalog.json',
        ],
    }
